"""Add content_type and reviewer_score to generated_posts

Revision ID: 55feb1f3514d
Revises: b37877c7908a
Create Date: 2026-07-08 18:15:17.612932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55feb1f3514d'
down_revision: Union[str, Sequence[str], None] = 'b37877c7908a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_posts', sa.Column('content_type', sa.String(length=30), nullable=True))
    op.add_column('generated_posts', sa.Column('reviewer_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_posts', 'reviewer_score')
    op.drop_column('generated_posts', 'content_type')
    # ### end Alembic commands ###
