"""Add generated_posts, post_reviews, publishing_jobs

Revision ID: b37877c7908a
Revises: 88a2decc188d
Create Date: 2026-07-08 17:12:14.471872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b37877c7908a'
down_revision: Union[str, Sequence[str], None] = '88a2decc188d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_posts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('generation_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cta', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWER_PASSED', 'REVIEWER_FAILED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', 'SKIPPED', name='generated_post_status'), server_default='DRAFT', nullable=False),
    sa.Column('reviewer_notes', sa.String(), nullable=True),
    sa.Column('regenerate_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_posts_generation_cycle_id'), 'generated_posts', ['generation_cycle_id'], unique=False)
    op.create_index(op.f('ix_generated_posts_status'), 'generated_posts', ['status'], unique=False)
    op.create_index(op.f('ix_generated_posts_workspace_id'), 'generated_posts', ['workspace_id'], unique=False)
    op.create_table('post_reviews',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'REGENERATE', 'SKIP', 'EDIT', name='post_review_action'), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('edited_caption', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['generated_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_reviews_post_id'), 'post_reviews', ['post_id'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'PUBLISHED', 'FAILED', 'RETRYING', name='publishing_job_status'), server_default='QUEUED', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['generated_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_jobs_post_id'), 'publishing_jobs', ['post_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_status'), 'publishing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_workspace_id'), 'publishing_jobs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_jobs_workspace_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_status'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_post_id'), table_name='publishing_jobs')
    op.drop_table('publishing_jobs')
    op.drop_index(op.f('ix_post_reviews_post_id'), table_name='post_reviews')
    op.drop_table('post_reviews')
    op.drop_index(op.f('ix_generated_posts_workspace_id'), table_name='generated_posts')
    op.drop_index(op.f('ix_generated_posts_status'), table_name='generated_posts')
    op.drop_index(op.f('ix_generated_posts_generation_cycle_id'), table_name='generated_posts')
    op.drop_table('generated_posts')
    # ### end Alembic commands ###
